/*
 * Copyright (C) 2018 Intel Corporation. All rights reserved.
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef PRELAUNCHED_VM0_H
#define PRELAUNCHED_VM0_H

#define	VM0_CONFIGURED

#define VM0_CONFIG_NAME				"ACRN PARTITION VM 1 for DNV-CB2"
#define VM0_CONFIG_TYPE				PRE_LAUNCHED_VM
#define VM0_CONFIG_PCPU_BITMAP			(PLUG_CPU(0) | PLUG_CPU(2) | PLUG_CPU(4) | PLUG_CPU(6))
#define VM0_CONFIG_FLAGS			LAPIC_PASSTHROUGH
#define VM0_CONFIG_MEM_START_HPA		0x100000000UL
#define VM0_CONFIG_MEM_SIZE			0x80000000UL

#define VM0_CONFIG_OS_NAME			"ClearLinux 26600"
#define VM0_CONFIG_OS_BOOTARGS			"root=/dev/sda rw rootwait noxsave maxcpus=4 nohpet console=hvc0 " \
						"console=ttyS0 no_timer_check ignore_loglevel log_buf_len=16M "\
						"consoleblank=0 tsc=reliable xapic_phys  apic_debug"

#define VM0_CONFIG_PCI_PTDEV_NUM		2U

#define VM0_CONFIG_PCI_PTDEV0_CONFIGURED
#define VM0_CONFIG_PCI_PTDEV0_NAME		"Hostbridge"
#define VM0_CONFIG_PCI_PTDEV0_VBUS		0x00U
#define VM0_CONFIG_PCI_PTDEV0_VDEV		0x00U
#define VM0_CONFIG_PCI_PTDEV0_VFUN		0x00U
#define VM0_CONFIG_PCI_PTDEV0_PBUS		0x00U
#define VM0_CONFIG_PCI_PTDEV0_PDEV		0x00U
#define VM0_CONFIG_PCI_PTDEV0_PFUN		0x00U

#define VM0_CONFIG_PCI_PTDEV1_CONFIGURED
#define VM0_CONFIG_PCI_PTDEV1_NAME		"Ethernet Controller"
#define VM0_CONFIG_PCI_PTDEV1_VBUS		0x00U
#define VM0_CONFIG_PCI_PTDEV1_VDEV		0x01U
#define VM0_CONFIG_PCI_PTDEV1_VFUN		0x00U
#define VM0_CONFIG_PCI_PTDEV1_PBUS		0x03U
#define VM0_CONFIG_PCI_PTDEV1_PDEV		0x00U
#define VM0_CONFIG_PCI_PTDEV1_PFUN		0x01U

#define VM0_CONFIG_PCI_PTDEV2_CONFIGURED
#define VM0_CONFIG_PCI_PTDEV2_NAME		"USB Controller"
#define VM0_CONFIG_PCI_PTDEV2_VBUS		0x00U
#define VM0_CONFIG_PCI_PTDEV2_VDEV		0x02U
#define VM0_CONFIG_PCI_PTDEV2_VFUN		0x00U
#define VM0_CONFIG_PCI_PTDEV2_PBUS		0x00U
#define VM0_CONFIG_PCI_PTDEV2_PDEV		0x15U
#define VM0_CONFIG_PCI_PTDEV2_PFUN		0x00U

#endif /* PRELAUNCHED_VM0_H */
